# Generated by Django 5.2.1 on 2025-05-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_blocked',
            new_name='is_block',
        ),
    ]
