# Dockerfile.client
FROM node:22

WORKDIR /client

COPY ./client/package*.json ./

RUN npm cache clean --force && \
    rm -rf node_modules && \
    npm install

COPY ./client .

ENV HOST=0.0.0.0

CMD ["npm", "run", "dev"]
