version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - pngnet
    ports:
      - "3000:80"
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    networks:
      - pngnet
    ports:
      - "3001:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCOUNT_HASH=${CLOUDFLARE_ACCOUNT_HASH}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_IMAGE_DOMAIN=${CLOUDFLARE_IMAGE_DOMAIN}
      - CLOUDFLARE_ENDPOINT=${CLOUDFLARE_ENDPOINT}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    depends_on:
      - redis
      - postgres
    networks:
      - pngnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pngnet

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pngnet

  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./backend/static:/backend/static:ro
      - ./backend/media:/backend/media:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./dashboard/dist:/usr/share/nginx/dashboard:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    networks:
      - pngnet

volumes:
  postgres_data:

networks:
  pngnet:
    driver: bridge
