# Dockerfile.dashboard
FROM node:22

WORKDIR /dashboard

COPY ./dashboard/package*.json ./

RUN npm cache clean --force && \
    rm -rf node_modules && \
    npm install

COPY ./dashboard .

ENV HOST=0.0.0.0

CMD ["npm", "run", "dev"]
