# version: "3.9"

# services:
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile.client
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./client:/client
#       - ./client/node_modules:/client/node_modules
#     environment:
#       - HOST=0.0.0.0

#   dashboard:
#     build:
#       context: .
#       dockerfile: Dockerfile.dashboard
#     ports:
#       - "5174:5173"
#     volumes:
#       - ./dashboard:/dashboard
#       - ./dashboard/node_modules:/dashboard/node_modules
#     environment:
#       - HOST=0.0.0.0

#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/backend
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - CELERY_RESULT_BACKEND=redis://redis:6379/0
#       - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
#       - CLOUDFLARE_ACCOUNT_HASH=${CLOUDFLARE_ACCOUNT_HASH}
#       - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
#       - CLOUDFLARE_IMAGE_DOMAIN=${CLOUDFLARE_IMAGE_DOMAIN}
#       - CLOUDFLARE_ENDPOINT=${CLOUDFLARE_ENDPOINT}
#       - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
#     depends_on:
#       - redis

#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6379:6379"

#   nginx:
#     image: nginx:1.24
#     ports:
#       - "80:80"
#     depends_on:
#       - client
#       - backend
#       - dashboard
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./backend/static:/backend/static
#       - ./backend/media:/backend/media

version: "3.9"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - ./client/node_modules:/client/node_modules
    environment:
      - HOST=0.0.0.0

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "5174:5173"
    volumes:
      - ./dashboard:/dashboard
      - ./dashboard/node_modules:/dashboard/node_modules
    environment:
      - HOST=0.0.0.0

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCOUNT_HASH=${CLOUDFLARE_ACCOUNT_HASH}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_IMAGE_DOMAIN=${CLOUDFLARE_IMAGE_DOMAIN}
      - CLOUDFLARE_ENDPOINT=${CLOUDFLARE_ENDPOINT}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:1.24
    ports:
      - "80:80"
    depends_on:
      - client
      - dashboard
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/backend/static
      - ./backend/media:/backend/media
