// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/image/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/image/:slug";
  };
  "routes/home/index.tsx": {
    id: "routes/home/index";
    page: "/";
  };
  "routes/single/single.tsx": {
    id: "routes/single/single";
    page: "/image/:slug";
  };
};