# Generated by Django 5.2.1 on 2025-05-15 06:41

import accounts.utils
import app.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(blank=True, help_text='Upload your photo...', null=True, upload_to=accounts.utils.USER_DIRECTORY_PATH, verbose_name='Image')),
                ('username', models.CharField(db_index=True, help_text='Enter your username...', max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')], verbose_name='Username')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Enter your email address...', max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(10), app.utils.validate_email], verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, help_text='Enter your first name...', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), app.utils.validate_alpha], verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Enter your last name...', max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(3), app.utils.validate_alpha], verbose_name='Last Name')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Enter your role...', max_length=10, verbose_name='Role')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_block', models.BooleanField(default=False, verbose_name='Is Block')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined Date')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
