# Generated by Django 5.2.1 on 2025-05-15 06:12

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload your image file...', upload_to='images/', validators=[app.utils.validate_image_extension, app.utils.validate_image_dimensions], verbose_name='Image')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', help_text='Enter the status of the image.', max_length=20, verbose_name='Status')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded')),
            ],
        ),
    ]
