# Generated by Django 5.2.1 on 2025-05-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('imageMetaData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='image_upload.imagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaDataKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('imageMetaData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='image_upload.imagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetaDataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('imageMetaData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='image_upload.imagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imageMetaData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image_upload.imagemetadata')),
            ],
        ),
    ]
