# Generated by Django 5.2.1 on 2025-06-04 10:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudflareimagemodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cloudflareimagemodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CloudflareImageKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=80, null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('cloudflareImageModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudflareImageKeywords', to='image_upload.cloudflareimagemodel')),
            ],
        ),
    ]
