# Generated by Django 5.2.1 on 2025-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemetadatakeyword',
            name='imageMetaData',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='imageMetaData',
        ),
        migrations.RemoveField(
            model_name='imagemetadatacategory',
            name='imageMetaData',
        ),
        migrations.DeleteModel(
            name='ImageMetaDataTag',
        ),
        migrations.DeleteModel(
            name='ImageMetaDataKeyword',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.DeleteModel(
            name='ImageMetaData',
        ),
        migrations.DeleteModel(
            name='ImageMetaDataCategory',
        ),
    ]
